services:
  nextjs:
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  dotnet-api:
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  postgres:
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  nginx:
    restart: always
